### PR TITLE
Update transformers version in setup.cfg

### PR DESCRIPTION
**Pull request by gthb**
Same as in requirements.txt

### CODE REVIEW

**Comment by adrianeboyd** [comment]
Thanks, sorry I missed that!

(Do we want to add the same kind of new dependency tests here as in spacy?)

**Comment by gthb** [comment]
> (Do we want to add the same kind of new dependency tests here as in spacy?)

In case that's addressed to me :) — I'm not familiar with the “new dependency tests” in spacy.

**Comment by adrianeboyd** [comment]
Not addressed to you, sorry that was confusing!

**Comment by adrianeboyd** [comment]
Thanks again for catching this! It looks like `2.4.0` is also compatible, so I'm going to lower it to `2.4.0` in both cases instead of merging this.

**Pull request closed without merging**
