### PR TITLE
WIP: Fix IO after init_model

### LINKED ISSUE #117: Transformers-Compatibility Issue with SerializableDistilBertTokenizer
spacy-transformers: 0.5.1
transformers: 2.3.0

Hi,

today I wanted to follow [HuggingFace's DistilBERT](https://github.com/huggingface/transformers/tree/master/examples/distillation) for the german pretrained model. Following [this reply from @ines ](https://github.com/explosion/spacy-transformers/issues/81) I downloaded the `vocab.txt`, `distilbert-base-german-cased-pytorch_model.bin` and the `bert_config.json`, executed the `init_model.py` and got the following result:

```
(ea_env) C:\Users\xx\PycharmProjects\word_embeddings\pretrained_models>python init_model.py --lang de --name distilbert-base-german-cased distilbert-base-german-cased
ℹ Creating model for 'distilbert-base-german-cased' (de)
✔ Initialized the model pipeline
✔ Saved 'distilbert-base-german-cased' (de)
Pipeline: ['sentencizer', 'trf_wordpiecer', 'trf_tok2vec']
Location: distilbert-base-german-cased
✔ Model loads!
```

which looks good. Loading the model in spacy by providing the absolute path to spacy.load("..."), no error is thrown. However if I want to parse a sentence with Spacy, the following error occurs:

```
>>> parsed_sentence = nlp(sentence)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xx\Envs\eva_env\lib\site-packages\spacy\language.py", line 435, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "C:\Users\xx\Envs\eva_env\lib\site-packages\spacy_transformers\pipeline\wordpiecer.py", line 50, in __call__
    pieces = self.predict([doc])
  File "C:\Users\xx\Envs\eva_env\lib\site-packages\spacy_transformers\pipeline\wordpiecer.py", line 93, in predict
    seg_words = self.model.tokenize(segment.text)
  File "C:\Users\xx\Envs\eva_env\lib\site-packages\transformers\tokenization_utils.py", line 656, in tokenize
    if self.init_kwargs.get('do_lower_case', False):
AttributeError: 'SerializableDistilBertTokenizer' object has no attribute 'init_kwargs'
```

As far as I have read, DistilBERT is natively supported by the `transformers` library thus it should be by `spacy-transformers` or am I wrong? Now I have seen, that a requirement for spacy-tranformers is transformers <2.1.0. Do you think the error is related to a version conflict?

Regards and merry christmas
Julian

### PR DESCRIPTION
**Pull request by svlandeg**
To create a `distilbert-base-german-cased` model with the `init_model.py` script, I had to add two additional fields to the serialization code.

Fixes #117

### CODE REVIEW

**Comment by JulianGerhard21** [comment]
Hi @svlandeg ,

since e.g. `de_trf_bertbasecased_lg` currently doesn't have the field "`unique_added_tokens_encoder`" we should maybe `try/catch` the case that a field can't be set. Currently, it leads to a KeyError.

Any ideas?

Kind regards
Julian

**Comment by svlandeg** [comment]
Yes, you're probably right. As the fields in the original transformer source code may change, we'll have to be clever about being flexible I suppose ?

**Comment by JulianGerhard21** [comment]
Jeah indeed - I'll think about it over night and get back to you asap.

**Comment by svlandeg** [comment]
This edit got merged as part of the [PR 138](https://github.com/explosion/spacy-transformers/pull/138/files), which doesn't account for backwards compatibility but pins `transformers>=2.5.0,<2.6.0`.

**Pull request closed without merging**
