### PR TITLE
Extend transformers to <4.10.0

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Comment by bryant1410** [comment]
What about using dependabot? So PRs such as this one are automated.

It probably wouldn't handle having both `requirements.txt` and `setup.cfg`, but I think you can get rid of the former and do `pip install -e .` in the Azure pipelines file instead of maintaining both files.

**Comment by adrianeboyd** [comment]
Thanks for the PR!

In our repos `requirements.txt` includes developer and test dependencies that aren't in `setup.cfg`, so we wouldn't want to get rid of it. We also want to test from a vanilla sdist install in the CI so we catch problems that you might not see with an editable install.

In `spacy` some dependencies are in four places (one of them is actually useless, but kept for historical reasons/reference, I guess? I've considered getting rid of it but it's so hard to follow `setuptools` changes that I'm not sure if it might still be used in some old version somewhere) and we have tests in the test suite to catch if they get out-of-sync with each other, but no automatic checks for updates.

If dependabot can only handle the update in one spot, it might be a bit frustrating in practice, and we are rarely under time pressure to make updates because of security vulnerabilities, but we can think about adding it...

**Comment by bryant1410** [comment]
> In our repos `requirements.txt` includes developer and test dependencies that aren't in `setup.cfg`, so we wouldn't want to get rid of it. We also want to test from a vanilla sdist install in the CI so we catch problems that you might not see with an editable install.
> 
> In `spacy` some dependencies are in four places (one of them is actually useless, but kept for historical reasons/reference, I guess? I've considered getting rid of it but it's so hard to follow `setuptools` changes that I'm not sure if it might still be used in some old version somewhere) and we have tests in the test suite to catch if they get out-of-sync with each other, but no automatic checks for updates.

Thanks for the detailed explanation! I wonder, have you folks considered Poetry? It has the concept of dev-dependencies.

> If dependabot can only handle the update in one spot, it might be a bit frustrating in practice, and we are rarely under time pressure to make updates because of security vulnerabilities, but we can think about adding it...

I'm actually not sure about it, was just guessing. Worth giving a shot sometime?

**Comment by adrianeboyd** [comment]
I think using poetry would be a pretty major change vs. our current wheel building setup [`wheelwright`](https://github.com/explosion/wheelwright), which uses [`multibuild`](https://github.com/matthew-brett/multibuild).

We'll keep dependabot in mind...

**Comment by bryant1410** [comment]
One more thing about dependabot: in the GitHub settings, it says which files it's checking (e.g., `requirements.txt`).

**Pull request merged**
