### PR TITLE
Set transformers upper bound to < 4.42.0

### PR DESCRIPTION
**Pull request by danieldk**
## Description

Relax the upper bound a little.

### Types of change

Maintenance

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [ ] My changes don't require a change to the documentation, or if they do, I've added all required information.

### CODE REVIEW

**Review by gregorybchris — APPROVED** [review]

**Comment by gregorybchris** [comment]
Thanks for the update! Our team would love to pull the new version whenever you publish

**Comment by hume-brian** [comment]
@danieldk can we get an update here on when this might be merged/deployed?

**Comment by thsunkid** [comment]
@danieldk, thanks for the update. Do you have a plan to release this update in a new version soon?

**Comment by svlandeg** [comment]
Hi all! Please don't ping individual maintainers, as it makes our GH notifications difficult to use 🙏 

We're preparing a release with this update now, and I'll update here when it's available.

**Pull request merged**
